#!/usr/bin/env python
# -*- coding: utf-8 -*- #
from __future__ import unicode_literals

AUTHOR = u'Andrew Becker'
SITENAME = u'acbecker.github.io'
SITESUBTITLE = u"Astrophysics, Statistics, and Computer Science"
SITEURL = '' # change in publishconf.py

# RSS/Atom feeds
FEED_DOMAIN = SITEURL
FEED_ATOM = 'atom.xml'


# Times and dates
#DEFAULT_DATE_FORMAT = "%Y-%m-%dT%H:%M:%S"
DEFAULT_DATE_FORMAT = "%Y-%m-%d"
TIMEZONE = 'US/Pacific'
DEFAULT_LANG = u'en'

# Feed generation is usually not desired when developing
FEED_ALL_ATOM = None
CATEGORY_FEED_ATOM = None
TRANSLATION_FEED_ATOM = None

# Title menu options
MENUITEMS = [('Archives', '/archives.html'),
             ('Home Page', 'http://www.astro.washington.edu/users/becker')]
NEWEST_FIRST_ARCHIVES = True


## Blogroll
#LINKS =  (('Pelican', 'http://getpelican.com/'),
#          ('Python.org', 'http://python.org/'),
#          ('Jinja2', 'http://jinja.pocoo.org/'),
#          ('You can modify those links in your config file', '#'),)

# Social widget
SOCIAL = (#('<i class="icon-rss"></i> RSS', "%s/%s" % (FEED_DOMAIN, FEED_ATOM)),
          ('<i class="icon-github"></i> Github', 'http://www.github.com/acbecker'),
          ('<i class="icon-linkedin-sign"></i> LinkedIn', 'http://www.linkedin.com/in/acbecker'),
          ('<i class="icon-twitter"></i> Twitter', 'http://twitter.com/the__fog'),
          )

DEFAULT_PAGINATION = 10

# Uncomment following line if you want document-relative URLs when developing
#RELATIVE_URLS = True

# intalled
#THEME = 'notmyidea'
# local
THEME = '/astro/store/shared-scratch1/acbecker/LSST/lsst_devel/pelican-octopress-theme'

# static files to copy into root, very useful for robots.txt
#FILES_TO_COPY = (
#   ('extra/robots.txt', 'robots.txt'),
#   ('extra/humans.txt', 'humans.txt'),
#)

# directories to be copied into output/static/
STATIC_OUT_DIR = ''
STATIC_PATHS = ['images', 'css', 'js']

# very useful for debugging purposes
DELETE_OUTPUT_DIRECTORY = True

ARTICLE_URL = 'blog/{date:%Y}/{date:%m}/{date:%d}/{slug}/'
ARTICLE_SAVE_AS = 'blog/{date:%Y}/{date:%m}/{date:%d}/{slug}/index.html'

PLUGIN_PATH = '/astro/store/shared-scratch1/acbecker/LSST/lsst_devel/pelican-plugins'
PLUGINS = []

# publishconf.py
## to get comments, etc
#DISQUS_SITENAME = "acbeckerblog" 
## GITHUB_URL = "https://github.com/acbecker" # Don't really want the "fork me" banner
#GOOGLE_ANALYTICS = "UA-42642734-1"

# Sharing
TWITTER_USER = 'the__fog'
GOOGLE_PLUS_USER = 'acbecker'
GOOGLE_PLUS_ONE = True
GOOGLE_PLUS_HIDDEN = False
FACEBOOK_LIKE = False
TWITTER_TWEET_BUTTON = True
TWITTER_LATEST_TWEETS = True
TWITTER_FOLLOW_BUTTON = True
TWITTER_TWEET_COUNT = 3
TWITTER_SHOW_REPLIES = 'false'
TWITTER_SHOW_FOLLOWER_COUNT = 'true'

# This header file is automatically generated by the notebook plugin
# Modified /astro/store/shared-scratch1/acbecker/LSST/lsst_devel/pelican-octopress-theme/templates/base.html
# to say
#  {% if EXTRA_HEADER %}
#    {{ EXTRA_HEADER }}
#  {% endif %}
# Not sure if this actually did anything tho...
EXTRA_HEADER = open('_nb_header_mod.html').read().decode('utf-8')

# Trying to get the Category panel off the RHS, no effect.
CATEGORY_SAVE_AS = False
